# .travis.yml

language: r
sudo: false
warnings_are_errors: false

matrix:
  include:
  - r: devel
  - r: release

r_packages: 
  - httr
  - reshape2
  - stringr
  - tidyr
  - RCurl
  - SPARLQL

env:
  global:
   - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE

before_install:
  - cd pkg/paracelsus
 
